= The Plan

A man without a plan, is a man planning to fail! In this lecture we will go through our _10-step plan_ on how to migrate an AngularJS application to Angular. So lets get started!

==== 1. Single Responsibility
Follow single responsibility by making sure each file always contains only a single entity.

==== 2. TypeScript & Webpack

Add TypeScript & Webpack. Seriously, do it. This will make your life a lot easier as we make our way through the migration process.

==== 3. AngularJS 1.5

Migrate to at least AngularJS 1.5 to make use of `components` when converting your application to Angular.

==== 4. Component'ify

Breakdown your AngularJS code into components.

==== 5. Modernize

Modernize your AngularJS application with modern Javascript and TypeScript techniques.

==== 6. Dual Boot
Dual boot your application with both AngularJS and Angular at the same time.

==== 7. Services -> Angular
Convert all AngularJS services to Angular services.

==== 8. Components -> Angular
Convert all AngularJS components to Angular components.

==== 9. Routing -> Angular
Take all Routing and convert it into Angular in one go.

==== 10. Remove AngularJS
Finally, lets clear out the mess to see our migrated application in all its glory!
