= Course Structure

Welcome to the second lecture of the series! Before we get into the good stuff, let's have a quick look at how this course is structured.

== Mental Model

At the risk of sounding like a broken record, let me repeat myself. Migrating from AngularJS to Angular is going to be messy, hard work and your specific instance of migration is going to be vastly different from everyone elses.

But underlying all the chaos is a simple structure and a clear set of rules. If you have a good grasp of this, you will be able to see through the inherent complexities of migration which brings us to the first goal of this course:

*To give you a mental model of the underlying structure and rules of your problem to guide you through the minefield of migration.*


== Plan

A person without a plan is a person planning to fail. So what is the plan?

In this section, I will teach you my strategy, the strategy that I advocate when migrating an AngularJS application. It is generic, applicable to any of your AngularJS migration projects and one that I have used with great success.

Of course, there is no steadfast rule that _says_ you have to follow my plan, but it is what I recommend you follow and it will be the method that I will teach in this course.


== Case Study

The meat of this course is going to be a __real case study__. We are going to take a real-world application, break it down and migrate it from AngularJS to Angular using our plan. In fact, if you have followed my other courses you might already be familiar with this. It is the very same contacts application that we built-in my old AngularJS course.


== Troubleshooting

Based on my experience delivering AngularJS to Angular migration workshops, one thing I can guarantee you is that there will be problems. Fear not, the troubleshooting section will discuss some of the more common issues that seem to always pop up during a migration project. Hopefully, some of it might be useful for you as well.


== Alternative Migration Strategy
The strategy that I will discuss here is not mandated by the Angular team but it is something that I have presented and talked about at many conferences, including the Angular connect conference in London. It is a catch-all, bulletproof migration strategy that could work for you.

If everything fails and you are looking at a complete rewrite of your AngularJS application, this might just be what you are looking for.
